export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as NotFound } from "./NotFound";
export { default as Services } from "./Services";
export { default as Signup } from "./Signup";
export { default as Profile } from "./Profile";
export { default as Dashboard } from "./Dashboard";
